### ISSUE TITLE
deployment: tls ingress=true doesn't seem to reference to any secret

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#1097]
having an custom override like this, doesn't seem to create an ingress with tls annotations. It's only when you add `selfSigned` or `certManager` annotations that it does.

```yaml
controlplane:
    ingressAPI:
      enabled: true
      tls: true
      hostname: test.kong.local
```

resulting ingress
```yaml
  spec:                                                              
    ingressClassName: kong                                                                                                                
    rules:                                                           
    - host: test.kong.local                                          
      http:                                                          
        paths:                                                       
        - backend:                                                   
            service:                                                 
              name: chainloop-controlplane-api                                                                                            
              port:                                                  
                name: grpc                                           
          path: /                                                    
          pathType: ImplementationSpecific            
```
