### ISSUE TITLE
Create description and labels fields in policy spec

### ISSUE THREAD

**Issue by jiparis** [chainloop-dev/chainloop#1126]
This new metadata will help on usability and groping of policies.

```
apiVersion: workflowcontract.chainloop.dev/v1
kind: Policy
metadata:
  name: sbom-present
  description: Checks that a SBOM material is present, in either CycloneDX or SPDX format
  labels:
    category: sbom
spec:
...
```
