### ISSUE TITLE
Support remote policies

### ISSUE THREAD

**Issue by jiparis** [chainloop-dev/chainloop#1180]
The goal of this task is to add support for organization owned policies, stored in an external repository.

Currently, any policy author can specify remote policies by providing an external public URL. But this might not be enough for private or builtin policies, that organizations don't want to expose publicly, but still want to keep in a central repository. For this purpose, we propose allowing the configuration of "Policy providers", consisting of an external service that will provide the policy material on request.

Policies will be referenced by name, optionally prepending a provider name:

```
apiVersion: workflowcontract.chainloop.dev/v1
kind: Policy
metadata:
  name: sarif-errors
spec:
  ref: policy-name # or chainloop://policy-name
```

On `contract create`, Chainloop would query the provider to verify that the reference is valid.
On `contract describe`, Chainloop will query the provider to retrieve the policy material and embed it in the resulting payload. This way, the CLI doesn't need to know anything about providers, since all the policies will be already in the contract.

The policy provider service would accept Chainloop API_TOKEN for Bearer authentication.
