### ISSUE TITLE
Load file-based policy regos relative to the policy path

### ISSUE THREAD

**Issue by jiparis** [chainloop-dev/chainloop#1411]
When creating detached policies, currently it's expected that the rego script reference has an absolute file path. For example, given this folder structure:
```
> tree test
test
├── my-policy.yaml
├── my-rego.rego
```
to be able to reference the policy in the attachment with `ref: file://test/my-policy.yaml`, all rego reference must have the same path:
```
spec:
  policies:
    - kind: SARIF
       ref: file://test/my-rego.rego
```
This is counter-intuitive, and goes against policy encapsulation, making it difficult to be moved, copied in different paths. Instead, a relative path would be easy to understand:
```
spec:
  policies:
    - kind: SARIF
       ref: file://my-rego.rego # <-- this path is relative to the enclosing policy yaml path. 
```
