### ISSUE TITLE
Add policy parameters to the spec

### ISSUE THREAD

**Issue by jiparis** [chainloop-dev/chainloop#1425]
Currently, parameters are implicit and there is no way to enforce nor validate policy attachments.

A first version could consist on a plain list of inputs, without type information (all strings), following the style of Github workflows, as in this example:

```
apiVersion: workflowcontract.chainloop.dev/v1
kind: Policy
metadata:
  name:  banned-components
spec:
  inputs:
      - name: author
        description: "commit author"
        required: true
        default: "myteam@acme.org"

  policies:
    - kind: SBOM_CYCLONEDX_JSON
      path: script.rego
```
