### ISSUE TITLE
Add requirement identifiers to policy attachment

### ISSUE THREAD

**Issue by jiparis** [chainloop-dev/chainloop#1529]
This feature request consist on being able to relate policy evaluations to organization's requirements. 
While it's up to each company to define what are those requirements in terms of SDLC and security, policy evaluations in Chainloop should correlate to them, to, for example, allowing SecOps team to have a full security overview based on their compliance requirements.
Requirement IDs can optionally be locked by using a `@version` suffix. Not that `version` in this context is up to the organization, and may consist of a semver version number, or a sha256 digest, for example.
The easiest way is to add such IDs at the policy attachment level (both in contracts and policy groups):
```
yaml
# my contract
policies:
  materials:
    - ref: artifact-signed
      requirements:
        - req-id1@v1.2.3
        - req-id2@v0.1
```
The above example can be read as: if `artifact-signed` policy succeeds, it will contribute to satisfy requirements `req-id1@v1.2.3` and `req-id2@v0.1`.
