### ISSUE TITLE
allow policy arguments with comma character

### ISSUE THREAD

**Issue by jiparis** [chainloop-dev/chainloop#1979]
Current behaviour interprets them as CSV, converting them to multivalued arguments. 

There should be a way to escape the `,` and skip the CSV conversion. For example:
```yaml
policies:
  materials:
    - ref: my-policy
      with:
        foo: bar\, baz
```
