### ISSUE TITLE
helm chart render problems with Helm 3.18

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#2067]
Latest version of Helm introduces a rendering problem in our chart

```
helm template foo ./chainloop --set development=true | grep cas_server -A 3
    cas_server:
      grpc:
        addr: foo-chainloop-cas-api:%!f(json.Number=)
      insecure: true
```
