### ISSUE TITLE
Getting started contract doesn't work

### ISSUE THREAD

**Issue by jiparis** [chainloop-dev/chainloop#2076]
Running the Getting Started with the provided contract fails:
```bash
> chainloop att init --workflow build --project test-app --contract https://raw.githubusercontent.com/chainloop-dev/chainloop/refs/heads/main/docs/examples/quickstart/quickstart-contract.yaml

ERR validation error: invalid attachment: error executing policy request: Post "http://localhost:8002/v1/policies/validate": dial tcp [::1]:8002: connect: connection refused
```

The contract contains policies that are trying to get retrieved and validated with a default policy provider configured in `config.devel.yaml` (which is also inexistent)
```yaml
policy_providers:
  - name: chainloop
    default: true
    url: http://localhost:8002/v1
```
