### ISSUE TITLE
Populate releases footer information

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#30]
Goreleaser has [a mechanism](https://goreleaser.com/customization/release/) to add additional footer metadata to each release.

We could leverage this feature to add next steps such as the following in our `.goreleaser.yml` file

```yml
# https://goreleaser.com/customization/release/
release:
  footer: |
    - Read the [documentation](https://docs.chainloop.dev)
    - Join our [Discord server](https://discord.gg/Sfw3HnRt)
```
