### ISSUE TITLE
auto-onboard reusable workflow issue

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#961]
With a configuration like this one, I get the following error

```yaml
  onboard_workflow:
    name: Onboard Chainloop Workflow
    uses: chainloop-dev/labs/.github/workflows/chainloop_onboard.yml@4173e015dbd5dc2a8802555c268da63d57bbe576
    with:
      project: "chainloop-platform"
      workflow_name: "chainloop-platform-backend-release-production"
    secrets:
      api_token: ${{ secrets.CHAINLOOP_TOKEN }}
```

```
ERR failed to create workflow: rpc error: code = InvalidArgument desc = validation error: "chainloop-platform-chainloop-platform-backend-release-production": must be no more than 63 characters
```

it seems that for some reason the workflow_name I provided gets prepended by the project name. To me that's unexpected since I provided the name explicitly.
